title: Meng Yuan
position: Ph.D. Student
affiliation: University of Waterloo
email: m33yuan (at) uwaterloo (dot) ca
keywords: Semiparametric inference; Empirical likelihood; Density ratio models.
#google_scholar: https://scholar.google.com/
#github_link: https://github.com/yaoyao-liu/minimal-light
#linkedin: https://www.linkedin.com/
avatar: ./assets/img/photo2.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
