title: Meng Yuan
position: Postdoctoral Research Fellow
affiliation: University of Waterloo
email: meng.yuan (at) uwaterloo (dot) ca
keywords: Semiparametric inference; Empirical likelihood; Density ratio models; data integration; non-probability survey samples.
#google_scholar: https://scholar.google.com/
#github_link: https://github.com/yaoyao-liu/minimal-light
#linkedin: https://www.linkedin.com/
avatar: ./assets/img/photo.png
#google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: This is the personal website for Meng Yuan (University of Waterloo).
canonical: https://mengyuan-uw.github.io/
remote_theme: yaoyao-liu/minimal-light
